# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "プログラミング実習講義3,4"
author: 上野 優  UENO, Masaru
copyright: "2025"

exclude_patterns: [.venv, .DS_Store, "**.ipynb_checkpoints", "README.md"]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: "https://github.com/m-ueno/begin-python-2025"
  branch: master # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: false
